name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify to Telegram about new commit
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            [${{ github.repository }}]
            New commit detected:
            
            ${{ github.event.commits[0].message }}!

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER_IP }} 'bash /var/www/deployFiles/nest-js-ksu-helper.sh'

      - name: Notify to Telegram about successful deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: | 
            [${{ github.repository }}]
            New commit successfully deployed! 
            
            ${{ github.event.commits[0].message }}!
            
            See changes: 
            https://github.com/${{ github.repository }}/commit/${{github.sha}}